# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ua-vNo_IbHBq8omjm3jXESkCvxq-YIKt
"""

pip install matplotlib

pip install yfinance

tesla = yf.Ticker("TSLA")
data = tesla.history(period="1mo")
data.reset_index(inplace=True)
first_five = data.head()
print(first_five)

income_statement = tesla.quarterly_income_stmt.T


last_five_revenue = income_statement[['Total Revenue']].tail(5)

print(last_five_revenue)

gme = yf.Ticker("gme")
gme_data = gme.history(period="1mo")
gme_data.reset_index(inplace=True)
first_five = gme_data.head()
print(first_five)

income_statement = gme.quarterly_income_stmt.T


last_five_revenue = income_statement[['Total Revenue']].tail(5)

print(last_five_revenue)

import matplotlib.pyplot as plt

def make_graph():

    gme = yf.Ticker("GME")
    data = gme.history(period="1mo")
    data.reset_index(inplace=True)


    plt.figure(figsize=(10, 5))
    plt.plot(data['Date'], data['Close'], marker='o', color='green')


    plt.title("GME (GameStop) Closing Stock Price - Last 1 Month")
    plt.xlabel("Date")
    plt.ylabel("Closing Price (USD)")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()


    plt.show()


make_graph()

def make_graph():
    tesla = yf.Ticker ("TSLA")
    data = tesla.history(period="1mo")
    data.reset_index (inplace=True)

    plt.figure (figsize=(10, 5))
    plt.plot(data['Date'], data['Close'] , marker='o', color='blue')
    plt.title("Tesla (TSLA) Closing Stock Price - Last 1 Month")
    plt.xlabel("Date")
    plt.ylabel ("Closing Price (USD)")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

make_graph()